defaults: &defaults
  working_directory: /tmp/gubal-library
  docker:
  - image: supamiu/circleci-node-wine


version: 2
jobs:
  setup:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: Install local dependencies
        command: npm install
    - run:
        name: Install functions dependencies
        command: cd functions && npm install && cd ../
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
        - node_modules
        - functions/node_modules
    - persist_to_workspace:
        root: /tmp
        paths:
        - gubal-library/*


  lint:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp
    - run:
        name: Lint code and JSON
        command: npm run lint


  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp
    - run:
        name: Building
        command: |
          npm run build
    - save_cache:
        key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - dist
    - persist_to_workspace:
        root: /tmp
        paths:
        - gubal-library/*


  deploy-web:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /tmp
    - run:
        name: Deploying web
        command: ./node_modules/.bin/firebase deploy -P default --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  flow:
    jobs:
    - setup
    - lint:
        requires:
        - setup
    - build:
        requires:
        - lint
    - deploy-web:
        requires:
        - build
        filters:
          branches:
            only: master

