export enum PageContainerTab {
  DETAILS = 'TABS.Details',
  COMMENTS = 'TABS.Comments',
  SCREENSHOTS = 'TABS.Screenshots',
  QUESTS  = 'TABS.Quests',
  INSTANCES = 'TABS.Instance',
  ENEMIES = 'TABS.Enemies',
  RECIPES = 'TABS.Recipes',
  CREATED_FROM = 'TABS.Created_from',
  SHOPS = 'TABS.Shops',
  SPECIAL_SHOPS = 'TABS.Special_shops',
  CURRENCY = 'TABS.Currency',
  GATHERING = 'TABS.Gathering',
  GUILD_LEVES = 'TABS.Guild_leves',
}
